# Generated by Django 5.0 on 2026-06-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='depense',
            table='depense',
        ),
    ]
