# Generated by Django 5.0 on 2026-06-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_alter_depense_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
